apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
